---
- name: Playbook to configure network
  hosts: all
  become: true
  environment:
    HTTP_PROXY: "{{ lookup('env','HTTP_PROXY', default=http_proxy | default('')) }}"
    HTTPS_PROXY: "{{ lookup('env','HTTPS_PROXY', default=https_proxy | default('')) }}"
    NO_PROXY: "{{ lookup('env','NO_PROXY', default=no_proxy | default('')) }}"
  vars:
    network_state:
      dns-resolver:
        config:
          search:
            - "{{ lookup('ansible.builtin.env', 'DOMAIN_NAME', default=domain_name) | lower }}"
  roles:
    - linux-system-roles.network
