- name: Configure Windows Proxy
  hosts: all
  tasks:
    # - name: Set a proxy to use for all protocols
    #   ansible.windows.win_http_proxy:
    #     proxy: 10.197.0.23:3128
    #     bypass:
    #       - <local>
    - name: Configure IE proxy settings to apply to all users
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\Internet Settings
        name: ProxySettingsPerUser
        data: 0
        type: dword
        state: present
    - name: Configure IE to use explicit proxy host
      ansible.windows.win_inet_proxy:
        auto_detect: true
        proxy: 10.197.0.23:3128
        bypass:
          - <local>
          - 169.254.169.254
